name = "GenomiccUtils"
uuid = "45214ce5-ea42-4256-97be-5000532e2146"
authors = ["Olivier Labayle <olabayle@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJLinearModels = "6ee0df7b-362f-4a72-a706-9e79364fb692"
MLJTransforms = "23777cdb-d90c-4eb0-a694-7c2b83d5c1d6"
MLJTuning = "03970b2e-30c4-11ea-3135-d1576263f10f"
MLJXGBoostInterface = "54119dfa-1dab-4055-a167-80440f4f7a91"
StatisticalMeasures = "a19d573c-0a75-4610-95b3-7071388c7541"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
DelimitedFiles = "1.9.1"
MLJBase = "1.12.1"
MLJLinearModels = "0.10.1"
MLJTransforms = "0.1.4"
MLJTuning = "0.8.9"
MLJXGBoostInterface = "0.3.13"
StatisticalMeasures = "0.3.3"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
